accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

improvo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("proposals.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

proposals/urls.py
from django.urls import path
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.urls import path, include
from .views import CustomPasswordChangeDoneRedirectView
from . import views

urlpatterns = [
    path("auth/password_change/done/", CustomPasswordChangeDoneRedirectView.as_view(), name="password_change_done_redirect"),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("proposals/", views.proposals, name="proposals"),
    path("proposals/proposal_submission", views.proposal_submission, name="proposal_submission"),
    path("proposals/proposal_details/<int:id>", views.proposal_details, name="proposal_details"),
    path("upvote/<int:proposal_id>/", views.upvote_proposal, name="upvote_proposal"),
]

accounts/models.py
from django.db import models

# Create your models here.

proposals/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import User

class Proposal(models.Model):

    STATUS_CHOICES = (
        (_("Entered"), _("Entered")),
        (_("In progress"), _("In progress")),
        (_("Finished"), _("Finished")),
        (_("Rejected"), _("Rejected")),
    )
    CATEGORY_CHOICES = (
        (_("General"), _("General")),
        (_("Classes"), _("Classes")),
        (_("Adminstrative"), _("Adminstrative")),
        (_("Technical"), _("Technical")),
    )

    title = models.CharField(max_length=255)
    content = models.TextField()
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default=_("Entered")
    )
    category = models.CharField(
        max_length=20, choices=CATEGORY_CHOICES, default=_("General")
    )
    upvotes_count = models.PositiveIntegerField(default=0)
    datetime = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, related_name='proposals', on_delete=models.CASCADE)

    @property
    def upvote_count(self):
        return self.upvotes.count()

    upvote_count_db = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.pk:
            super().save(*args, **kwargs)
            return

        self.upvote_count_db = self.upvotes.count()
        super().save(*args, **kwargs)


class Comment(models.Model):
    proposal = models.ForeignKey(
        Proposal, related_name="comments", on_delete=models.CASCADE
    )
    author = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Upvote(models.Model):
    proposal = models.ForeignKey(
        Proposal, related_name="upvotes", on_delete=models.CASCADE
    )
    user_id = models.CharField(max_length=32)
    created_at = models.DateTimeField(auto_now_add=True)

proposals/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class CustomUserCreationForm(UserCreationForm):
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta(UserCreationForm.Meta):
        fields = ('username', 'email', 'password1', 'password2')

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError("This username is already taken.")
        return username

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords do not match.")
        return password2

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.models import User


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

    def form_valid(self, form):

        username = form.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            form.add_error('username', 'This username is already taken.')
            return self.form_invalid(form)
        else:
            return super().form_valid(form)

proposals/views.py
from django.db.models import F
from django.utils.encoding import smart_bytes
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import gettext as _
from .models import Proposal, Comment, Upvote
from django.db.models import Q


def proposals(request):
    search_query = request.GET.get('search')
    if search_query:
        proposals = Proposal.objects.filter(
            Q(title__icontains=search_query) | Q(content__icontains=search_query)
        )
    else:
        proposals = Proposal.objects.all()

    return render(request, "all_proposals.html", {"proposals": proposals})


@login_required
def proposal_details(request, id):
    error_message = None
    proposal = get_object_or_404(Proposal, id=id)
    comments = Comment.objects.filter(proposal=proposal)
    upvote_count = proposal.upvotes.count()

    if request.method == "POST":
        text = request.POST.get("Text")

        if text:
            author = request.user
            Comment.objects.create(author=author, text=text, proposal=proposal)
            return redirect('proposal_details', id=id)
        else:
            error_message = _("Text is required!")

    return render(
        request,
        "proposal_details.html",
        {
            "proposal": proposal,
            "comments": comments,
            "error_message": error_message,
            "upvote_count": upvote_count,
        },
    )


@login_required
def proposal_submission(request):
    categories = Proposal.CATEGORY_CHOICES
    error_message = None

    if request.method == "POST":
        title = request.POST.get("Title")
        proposal_content = request.POST.get("Proposal")
        category = request.POST.get("Category")
        user = request.user

        if title and proposal_content and category:
            new_proposal = Proposal.objects.create(
                title=title, 
                content=proposal_content, 
                category=category,
                author=user
            )
            new_proposal.save()

            return redirect("home")
        else:
            error_message = _("Category, title, and/or proposal content are required.")

    return render(
        request,
        "proposal_submission.html",
        {"categories": categories, "error_message": error_message},
    )


def upvote_proposal(request, proposal_id):
    if request.method == "POST":
        proposal = get_object_or_404(Proposal, id=proposal_id)

        current_user = request.user

        if Upvote.objects.filter(
            proposal=proposal, user_id=current_user
        ).exists():
            Upvote.objects.filter(proposal=proposal, user_id=current_user).delete()
            proposal.upvotes_count = F("upvotes_count") - 1
            proposal.save()
            return redirect("proposal_details", id=proposal_id)

        else:
            proposal.upvotes_count = F("upvotes_count") + 1
            proposal.save()
            Upvote.objects.create(
                proposal=proposal, user_id=current_user
            )

        return redirect("proposal_details", id=proposal_id)


class CustomPasswordChangeDoneRedirectView(RedirectView):
    url = reverse_lazy('home')


def home(request):
    return render(request, "home.html")

proposals/templates/all_proposals.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "All proposals" %}{% endblock %}
{% block content %}

<div class="p-6 mt-10 bg-gray-800 border border-gray-200 rounded-lg shadow-md dark:border-gray-700 dark:bg-gray-800">
    <div class="mb-4 text-3xl font-bold tracking-tight text-center text-white dark:text-white">
        {% trans "All proposals" %}
    </div>
    <div class="my-4">
        <div class="max-w-md mx-auto">
            <form class="w-full max-w-md" method="GET" action="">
                <label class="mb-2 text-sm font-medium text-white sr-only dark:text-white" for="default-search">{% trans "Search" %}
                </label>
                <div class="relative">
                    <div class="absolute inset-y-0 flex items-center pointer-events-none start-0 ps-3">
                        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                            xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                        </svg>
                    </div>
                    <input
                        class="block w-full p-5 text-lg text-white bg-gray-700 border border-gray-600 rounded-lg ps-10 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                        name="search" type="text" placeholder="{% trans "Search" %}" />
                    <button
                        class="absolute bottom-2.5 end-2.5 rounded-lg bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 px-5 py-2.5 text-center text-lg font-medium text-white shadow-lg shadow-cyan-500/50 hover:bg-gradient-to-br focus:outline-none focus:ring-4 focus:ring-cyan-300 dark:shadow-lg dark:shadow-cyan-800/80 dark:focus:ring-cyan-800"
                        type="submit">{% trans "Search" %}
                    </button>
                </div>
            </form>
        </div>
        {% for proposal in proposals %}
        <div class="mx-20 mb-3">
            <div
                class="p-6 mx-6 my-10 transition duration-100 delay-100 bg-gray-900 border border-gray-200 rounded-lg shadow-lg ease-out-in from-gray-900 to-indigo-950 hover:-translate-y-1 hover:scale-125 hover:bg-gradient-to-r dark:border-gray-700 dark:bg-gray-900">
                <div class="card-body">
                    <a class="text-decoration-none" href="proposal_details/{{ proposal.id }}">
                        <div class="mb-3 text-xl card-title">{{ proposal.title }}</div>
                        <p class="mb-1 card-text">{% trans "From" %}: {{ proposal.author }}</p>
                        <p class="mb-1 card-text">{% trans "Category" %}: {{ proposal.category }}</p>
                        <p class="mb-1 card-text">{% trans "Submitted on" %}: {{ proposal.datetime }}</p>
                        <p class="mb-1 card-text">{% trans "Upvotes" %}: {{ proposal.upvote_count }}</p>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

proposals/templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static tailwind_tags %}
<html lang="en">

<head>
    {% tailwind_css %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body class="text-white bg-gradient-to-r from-indigo-950 to-black dark:text-white dark:bg-black">
    <div class="flex justify-center">
        <div class="lg:w-1/2">
            {% if user.is_authenticated %}
            <div class="mt-10 mb-8 text-4xl font-bold text-center">
                {% trans "Hello" %}, {{ user.username }}!
            </div>
            <div class="mb-3 text-center">
                {% if user.is_superuser or user.is_staff %}
                <a class="group relative mb-2 me-2 inline-flex items-center rounded-lg bg-gradient-to-br from-purple-600 to-blue-500 p-0.5 text-sm font-medium text-white hover:text-white focus:outline-none focus:ring-4 focus:ring-blue-800 group-hover:from-purple-600 group-hover:to-blue-500"
                    href="/admin">
                    <span
                        class="relative rounded-md bg-black dark:bg-gray-900 px-5 py-2.5 text-lg transition-all duration-75 ease-in group-hover:bg-opacity-0">{% trans "Admin section" %}</span></a>
                {% endif %}
                <a class="group relative mb-2 me-2 inline-flex items-center rounded-lg bg-gradient-to-br from-purple-600 to-blue-500 p-0.5 text-sm font-medium text-white hover:text-white focus:outline-none focus:ring-4 focus:ring-blue-800 group-hover:from-purple-600 group-hover:to-blue-500"
                    href="{% url 'password_change' %}">
                    <span
                        class="relative rounded-md bg-black dark:bg-gray-900 px-5 py-2.5 text-lg transition-all duration-75 ease-in group-hover:bg-opacity-0">{% trans "Change password" %}<span></a>
                <form class="inline" action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button
                        class="group relative mb-2 me-2 inline-flex items-center rounded-lg bg-gradient-to-br from-purple-600 to-blue-500 p-0.5 text-sm font-medium text-white hover:text-white focus:outline-none focus:ring-4 focus:ring-blue-800 group-hover:from-purple-600 group-hover:to-blue-500"
                        type="submit">
                        <span
                            class="relative rounded-md bg-black dark:bg-gray-900 px-5 py-2.5 text-lg transition-all duration-75 ease-in group-hover:bg-opacity-0">{% trans "Log out" %}</span>
                    </button>
                </form>
            </div>
            {% endif %}
            <div class="content">
                {% block content %}{% endblock %}
            </div>
            <div class="mt-4 mb-40 text-center">
                {% if not request.path == "/" %}
                <form class="inline" action="/" method="get">
                    <button
                        class="group relative mb-2 me-2 inline-flex items-center justify-center overflow-hidden rounded-lg bg-gradient-to-br from-purple-600 to-blue-500 p-0.5 text-lg font-medium text-white hover:text-white focus:outline-none focus:ring-4 focus:ring-blue-800 group-hover:from-purple-600 group-hover:to-blue-500"
                        type="submit">
                        <span
                            class="relative rounded-md bg-black dark:bg-gray-900 px-5 py-2.5 transition-all duration-75 ease-in group-hover:bg-opacity-0">
                            {% trans "Back" %}
                        </span>
                    </button>
                </form>

                {% endif %}
                {% if 'proposals/proposal_details/' in request.path %}
                <form class="inline" action="{% url 'proposals' %}" method="get">
                    <button
                        class="group relative mb-2 me-2 inline-flex items-center justify-center overflow-hidden rounded-lg bg-gradient-to-br from-purple-600 to-blue-500 p-0.5 text-lg font-medium text-white hover:text-white focus:outline-none focus:ring-4 focus:ring-blue-800 group-hover:from-purple-600 group-hover:to-blue-500">
                        <span
                            class="relative rounded-md bg-black dark:bg-gray-900 px-5 py-2.5 transition-all duration-75 ease-in group-hover:bg-opacity-0">
                            {% trans "Back to proposals" %}
                        </span>
                    </button>
                </form>

                {% endif %}
            </div>
        </div>
    </div>
</body>

</html>

proposals/templates/home.html
{% extends "base.html" %} {% load i18n %} {% block title %} {% trans "Improvo
Proposal System" %} {% endblock %} {% block content %}

{% if user.is_authenticated %}
<div class="p-6 bg-gray-800 border-gray-700 rounded-lg shadow-md mt-10border">
    <div class="mb-4 text-3xl font-bold tracking-tight text-center text-white">
        {% trans "Improvo Proposal System" %}
    </div>
    <div class="my-4 text-center">
        <div class="mb-2 text-lg">{% trans "Submit your own proposal" %}</div>
        <button class="my-4" type="button">
            <a class="mb-2 me-2 rounded-lg bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 px-5 py-2.5 text-center text-lg font-medium text-white shadow-lg shadow-purple-500/50 hover:bg-gradient-to-br focus:outline-none focus:ring-4 focus:ring-purple-800"
                href="{% url 'proposal_submission' %}">{% trans "Submit here!" %}</a>
        </button>
    </div>
    <div class="my-4 text-center">
        <div class="mb-2 text-lg">{% trans "List of submitted proposals" %}</div>
        <button class="my-4" type="button">
            <a class="text-md my-2 me-2 rounded-lg bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 px-5 py-2.5 text-center font-medium text-white shadow-lg shadow-purple-800/80 hover:bg-gradient-to-br focus:outline-none focus:ring-4 focus:ring-purple-800"
                href="{% url 'proposals' %}">{% trans "View submitted proposals" %}</a>
        </button>
    </div>
</div>
</div>
{% else %}

<div class="mt-10 mb-4 text-3xl font-bold tracking-tight text-center text-white">
    {% trans "Improvo Proposal System" %}
</div>
<div class="my-4 text-center">
    <div class="mb-2 text-lg">{% trans "You are not logged in" %}</div>
    <div class="flex justify-center mt-4">
        <button class="my-4 mr-2" type="button">
            <a class="text-whitehover:bg-gradient-to-br my-2 me-2 rounded-lg bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 px-5 py-2.5 text-center text-lg font-medium shadow-lg shadow-blue-800/80 focus:outline-none focus:ring-4 focus:ring-blue-800"
                href="{% url 'login' %}">{% trans "Log in" %}</a>
        </button>
        <button class="my-4 ml-2" type="button">
            <a class="my-2 mb-2 me-2 rounded-lg bg-gradient-to-r from-green-400 via-green-500 to-green-600 px-5 py-2.5 text-center text-lg font-medium text-white shadow-lg shadow-green-800/80 hover:bg-gradient-to-br focus:outline-none focus:ring-4 focus:ring-green-300"
                href="{% url 'signup' %}">{% trans "Sign up" %}</a>
        </button>
    </div>
</div>
{% endif %}

{% endblock %}

proposals/templates/main.html
<!DOCTYPE html>
{% load i18n %}

<html>
  <head>
    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
  </head>

  <title>{% block title %} {% endblock %}</title>

<body>
  <div>
    <a href="/admin">{% trans "Admin section" %}</a>
  </div
  <div class="container">
    <div class="cp-5 bg-grey text-grey text-center">
        {% if not request.path == "/" %}
        <p>
          <a href="/">{% trans "Back to main page" %}</a>
        </p>
        {% endif %} {% block content %} {% endblock %}
      </div>
    </div>
  </body>
</html>

proposals/templates/proposal_details.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{{ proposal.title }}{% endblock %}
{% block content %}

<div class="p-6 mt-10 bg-gray-800 border border-gray-700 rounded-lg shadow-md dark:border-gray-700 dark:bg-gray-800">
    <div class="row">
        <div>
            <div class="p-4 mb-4 rounded-lg bg-secondary">
                <div class="mb-10 text-3xl text-center">{{ proposal.title }}</div>
                <div class="p-6 mt-10 bg-gray-700 border-gray-700 rounded-lg shadow-md dark:bg-gray-700">
                    <div class="text-lg font-semibold">{% trans "Category" %}:
                        <span class="font-normal">{{ proposal.category }}</span>
                    </div>
                    <div class="text-lg font-semibold">{% trans "Status" %}: <span>{{ proposal.status }}</span></div>
                    <div class="text-lg font-semibold">{% trans "Submitted on" %}: <span>{{ proposal.datetime }}</span>
                    </div>
                    <div class="text-lg font-semibold">{% trans "From" %}: <span>{{ proposal.author }}</span></div>
                    <div class="mt-4 card">
                        <div
                            class="px-4 mt-2 bg-gray-800 border border-gray-700 rounded-lg shadow-md card-body dark:border-gray-700 dark:bg-gray-800">
                            <div class="mt-2 mb-8 text-xl font-bold text-center card-title">{% trans "Proposal" %}
                            </div>
                            <p class="mb-10 card-text">{{ proposal.content }}</p>
                        </div>
                    </div>
                    <div class="mt-3 text-center"><strong>{% trans "Upvotes" %}:</strong> {{ upvote_count }}</div>
                    <form class="text-center" action="{% url 'upvote_proposal' proposal.id %}" method="post">
                        {% csrf_token %}
                        <button
                            class="button text-md my-2 me-2 rounded-lg bg-gradient-to-r from-purple-500 via-purple-600 to-purple-700 px-5 py-2.5 text-center font-medium text-white shadow-lg shadow-purple-800/80 hover:bg-gradient-to-br focus:outline-none focus:ring-4 focus:ring-purple-300 dark:shadow-lg dark:shadow-purple-800/80 dark:focus:ring-purple-800"
                            data-toggle="tooltip" data-placement="top" type="submit"
                            title="{{ _('Upvote this proposal. If you have already, you can remove your upvote.') }}">
                            {% trans "Upvote" %}
                        </button>
                    </form>
                    {% if error_message %}
                    <p class="mt-3 text-danger">{{ error_message }}</p>
                    {% endif %}
                </div>
                <div class="container-xl">
                    <div class="mt-8 card">
                        <div class="card-body">
                            <div class="mt-20 text-xl text-center card-title">{% trans "Comments" %}</div>
                            <div class="mt-3 comments">
                                {% for comment in comments %}
                                <div>
                                    <div
                                        class="p-6 mx-10 my-10 transition duration-100 delay-100 bg-gray-900 border border-gray-700 rounded-lg shadow-lg ease-out-in from-gray-900 to-indigo-950 hover:-translate-y-1 hover:scale-125 hover:bg-gradient-to-r dark:border-gray-700 dark:bg-gray-900">
                                        <div class="card-body">
                                            <p class="mb-8 text-lg font-semibold comment-author">{{ comment.author }}
                                                {% trans "commented" %}:
                                            </p>
                                            <p class="mb-0 comment-text">{{ comment.text }}</p>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                                <div
                                    class="p-6 mx-10 my-4 mt-10 text-lg text-center bg-gray-900 border border-gray-700 rounded-lg shadow-md dark:border-gray-700 dark:bg-gray-900">
                                    {% trans "Leave a comment" %}
                                    <form class="mb-4 comment-form" method="post">
                                        {% csrf_token %}
                                        <div class="mb-3 form-group">
                                            <textarea
                                                class="form-control my-8 block w-full rounded-lg border border-gray-600 bg-gray-700 p-2.5 text-sm text-white focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                                                id="id_text" name="Text" rows="10"></textarea>
                                        </div>
                                        <button
                                            class="mx-auto mb-2 mt-10 flex rounded-lg bg-gradient-to-r from-green-400 via-green-500 to-green-600 px-5 py-2.5 text-center text-lg font-medium text-white shadow-lg shadow-green-500/80 hover:bg-gradient-to-br focus:outline-none focus:ring-4 focus:ring-green-800 dark:shadow-lg dark:shadow-green-800/80 dark:focus:ring-green-800"
                                            type="submit">{% trans "Submit" %}</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<script>
    $(document).ready(function() {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

proposals/templates/proposal_submission.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Submit proposal" %}{% endblock %}
{% block content %}

<div class="p-6 mt-10 bg-gray-800 border border-gray-700 rounded-lg shadow-md dark:border-gray-700 dark:bg-gray-800">
    <div class="flex justify-center mt-4">
        <div class="w-full max-w-md">
            <div class="mt-4 text-white bg-gray-800 card">
                <div class="card-header bg-secondary">
                    <div class="my-6 text-4xl font-medium text-center">{% trans "Submit proposal" %}</div>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-6 text-center">
                            <label class="block mt-10 mb-2 text-lg font-medium text-white dark:text-white"
                                for="id_category">{% trans "Category" %}</label>
                            <select
                                class="rounded-lg border border-gray-600 bg-gray-700 p-2.5 text-sm text-white focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                                id="id_category" name="Category">
                                {% for category_key, category_value in categories %}
                                <option value="{{ category_key }}">{{ category_value }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="my-10 text-center">
                            <label class="text-2xl font-medium text-white form-label"
                                for="id_title">{% trans "Title" %}</label>
                            <input
                                class="mt-4 block w-full rounded-lg border border-gray-600 bg-gray-700 p-2.5 text-lg text-white focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                                id="id_title" name="Title" type="text" value="{{ title }}" required>
                        </div>
                        <div class="mt-10 text-center">
                            <label class="text-2xl font-medium text-white form-label"
                                for="id_proposal">{% trans "Proposal" %}</label>
                            <textarea
                                class="form-control mt-4 block w-full rounded-lg border border-gray-600 bg-gray-700 p-2.5 text-sm text-white focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                                id="id_proposal" name="Proposal" rows="8">{{ proposal_content }}</textarea>
                        </div>
                        <div class="text-center">
                            <button
                                class="mx-auto mb-2 mt-10 flex rounded-lg bg-gradient-to-r from-green-400 via-green-500 to-green-600 px-5 py-2.5 text-center text-lg font-medium text-white shadow-lg shadow-green-500/80 hover:bg-gradient-to-br focus:outline-none focus:ring-4 focus:ring-green-800 dark:shadow-lg dark:shadow-green-800/80 dark:focus:ring-green-800"
                                type="submit">{% trans "Submit" %}</button>
                        </div>
                        {% if error_message %}
                        <p class="mt-3 text-danger">{{ error_message }}</p>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-700 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>